### ISSUE TITLE
About the pre-trained weights for EUSR

### ISSUE THREAD

**Issue by 2279209430** [idearibosome/srzoo#1]
Thanks for your excellent work!

When I use the EUSR codes with your provided pre-trained model eusr_x2.pb, eusr_x4.pb, eusr_x8.pb, it leads to the following error :

Data loss: not an sstable (bad magic number): perhaps your file is in a 
different file format and you need to use a different restore operator?

**Comment by 2279209430** [comment]
![微信图片_20220120144000](https://user-images.githubusercontent.com/30076115/150286909-cf36614e-cf50-447b-9d7c-a8d6b7ed277f.png)

**Comment by idearibosome** [comment]
Hi Bowen,

Unfortunately, the pb files are not compatible with the checkpoint files. The model files provided in this repository are in the "Frozen Graph" format, where the model parameters are converted to the constant values (i.e., not trainable).

**Comment by 2279209430** [comment]
Thanks for your prompt reply !  I have successfully used your test zoo. This is a great work that brings much convenience to us. Thank you !
